# Hugo Blox GitHub Action to convert Bibtex publications to Markdown-based webpages
name: Import Publications From Bibtex

# Require permission to create a PR
permissions:
  contents: write
  pull-requests: write

# Run workflow when a `.bib` file is added or updated in the `data/` folder
on:
  push:
    branches: ['main']
    paths: ['publications.bib']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugoblox:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4  # Upgraded to v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install academic==0.10.0  # Use a requirements.txt if you have multiple dependencies

      - name: Convert BibTeX to Markdown
        # Ensures the action runs only if the .bib file exists
        if: hashFiles('publications.bib') != ''
        run: academic import publications.bib content/publication/ --compact

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: import publications from BibTeX'
          title: "📚 Import Latest Publications from BibTeX"
          body: |
            This automated PR imports the latest publications from `publications.bib` to `content/publication/`.
            
            **Changes:**
            - Converted BibTeX to Markdown
            - Updated publication content
            
            **[View Documentation](https://github.com/GetRD/academic-file-converter)**
          base: main
          labels: automated-pr, content
          branch: hugoblox-import-publications
          delete-branch: true

      - name: Check outputs
        if: steps.cpr.outputs.pull-request-number
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
